@startuml
'https://plantuml.com/sequence-diagra

interface IDamageable
{
    public void TakeHit(Weapon weaponType)
}

interface IDoDamage
{
    public void ApplyDamage()
}

abstract class ScriptableObject
{

}

class Weapon extends ScriptableObject
{
    public int damage
    public float force
}

class CharacterController
{
    Unity's CharacterController
}


class Movement
{
    MovementFunctions
}

class PlayerCharacterController
{
    CoordinatingPlayers:
    - movement
    - Combat
}

'CombatBehaviour -> Weapon

PlayerCharacterController --> PlayerInputComponent
PlayerCharacterController --> CombatBehaviour
PlayerCharacterController --> Movement

@enduml
